xsuaaBinding: 
config:
  idp:
  pattern:
image:
  repository: docker-cloudsdk.docker.repositories.sap.ondemand.com/k8s-approuter
  tag: latest
resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "512Mi" 
    cpu: "1000m"