apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sdkjs-e2e-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/session-cookie-name: "JSESSIONID"
    cert.gardener.cloud/purpose: managed
spec:
  tls:
  - hosts:
    # Replace with root domain
    # Example:<REPLACE-ME>
    - cloud-sdk-js.sdktests.shoot.canary.k8s-hana.ondemand.com
    # Replace with subdomain which includes a wildcard for multi-tenancy, with the pattern: "*.Subdomain.Domain"
    # Example: "*.<REPLACE-ME>.<REPLACE-ME>"
    - "*.e2e.ingress.cloud-sdk-js.sdktests.shoot.canary.k8s-hana.ondemand.com"
    # Replace with domain for the connectivity-proxy, with the pattern: Subdomain.Domain
    # Example: <REPLACE-ME>.<REPLACE-ME>
    - connectivitytunnel.ingress.cloud-sdk-js.sdktests.shoot.canary.k8s-hana.ondemand.com
    secretName: secret-tls
  rules:
  # Replace with subdomain which includes a wildcard for multi-tenancy, with the pattern: "*.Subdomain.Domain"
  # Example: "*.<REPLACE-ME>.<REPLACE-ME>" 
  - host: "*.e2e.ingress.cloud-sdk-js.sdktests.shoot.canary.k8s-hana.ondemand.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: approuter-svc
            port:
              number: 8080
