apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "approuter-chart.fullname" . }}-config
data:
  {{- if .Values.config.idp }}
  xs-app.json: {{ printf "{\"welcomeFile\":\"/web-pages/index.html\",\"routes\":[{\"source\":\"/backend-app/(.*)\",\"target\":\"$1\",\"destination\":\"backend\",\"identityProvider\":\"%s\"},{\"source\":\"/web-pages/(.*)\",\"target\":\"$1\",\"localDir\":\"static-resources\",\"identityProvider\":\"%s\"}]}" .Values.config.idp .Values.config.idp | toPrettyJson }}
  {{- else }}
  xs-app.json: {{ .Values.config.json | toPrettyJson | quote }}
  {{ end -}}
