apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-chart.fullname" . }}-config
data:
  cloud_destination: {{ .Values.cloudDestination | quote }}
  onpremise_destination: {{ .Values.onPremiseDestination | quote }}
  principal_propagation_destination: {{ .Values.principalPropagationDestination | quote }}