apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}-svc
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 3000
  selector:
    {{- include "app-chart.selectorLabels" . | nindent 4 }}
