name: build

on:
  pull_request: ~
  push:
    branches: [main]
    paths:
      - 'samples/cds-sample-application/**'
permissions:
    pull-requests: write
    contents: write
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1
  tests:
    needs: [checks]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --depth=1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install all Dependencies
        run: npm run ci --workspaces
      - name: CDS Samples - Install Dependencies and Build Package
      - name: CDS Samples - Tests
        run:  |
          npm run ci-build --workspace=samples/cds-sample-application
          npm run test:e2e --workspace=samples/cds-sample-application
      - name: Resilience Examples - Tests
        run: npm run test --worksapce=samples/resilience-examples
      - name: HTTP Client Examples - Tests
        run: npm run test --workspace=samples/http-client-examples
  dependabot:
      needs: tests
      runs-on: ubuntu-latest
      if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
      steps:
        - name: Dependabot metadata
          id: metadata
          uses: dependabot/fetch-metadata@v1.3.6
          with:
            github-token: "${{ secrets.GITHUB_TOKEN }}"
        - name: Approve a PR
          run: gh pr review --approve "$PR_URL"
          env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        - name: Enable auto-merge for Dependabot PRs
          run: gh pr merge --auto --squash "$PR_URL"
          env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}